### ISSUE TITLE
Bug when typing non ban message in Discord Console

### ISSUE THREAD

**Issue by cjl032224** [Latch93/DiscordText#74]
- [Fri 20:51:05 ERROR net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    at LatchEssentials-1.2.jar//lmp.discord.chatMessageAdapters.LogPlayerBanFromDiscordConsole.onMessageReceived(LogPlayerBanFromDiscordConsole.java:24)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:405)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829)
    at LatchEssentials-1.2.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004)
    at LatchEssentials-1.2.jar//com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
    at LatchEssentials-1.2.jar//com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
    at LatchEssentials-1.2.jar//com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
    at LatchEssentials-1.2.jar//com.neovis

**Comment by cjl032224** [comment]
Resolved
